repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: flake8
        name: Flake8
        description: run flake8 on the local environment
        entry: poetry run flake8
        language: system
        types: [python]
        require_serial: true
